-- ID                               int                              对话ID
-- studentID                        int                              学生ID
-- giftType                         int                              礼物类型
-- content                          string                           对话内容
-- level                            int                              好感度等级

return {
	[100] = {
		studentID = 5010,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[101] = {
		studentID = 5010,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[102] = {
		studentID = 5010,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[103] = {
		studentID = 5010,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[104] = {
		studentID = 5010,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[105] = {
		studentID = 5010,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[106] = {
		studentID = 5010,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[107] = {
		studentID = 5010,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[108] = {
		studentID = 5010,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[109] = {
		studentID = 5010,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[110] = {
		studentID = 5010,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[111] = {
		studentID = 5010,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[112] = {
		studentID = 5010,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[113] = {
		studentID = 5010,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[114] = {
		studentID = 5010,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[115] = {
		studentID = 5010,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[116] = {
		studentID = 5010,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[117] = {
		studentID = 5010,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[118] = {
		studentID = 5011,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[119] = {
		studentID = 5011,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[120] = {
		studentID = 5011,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[121] = {
		studentID = 5011,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[122] = {
		studentID = 5011,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[123] = {
		studentID = 5011,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[124] = {
		studentID = 5011,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[125] = {
		studentID = 5011,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[126] = {
		studentID = 5011,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[127] = {
		studentID = 5011,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[128] = {
		studentID = 5011,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[129] = {
		studentID = 5011,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[130] = {
		studentID = 5011,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[131] = {
		studentID = 5011,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[132] = {
		studentID = 5011,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[133] = {
		studentID = 5011,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[134] = {
		studentID = 5011,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[135] = {
		studentID = 5011,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[136] = {
		studentID = 5012,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[137] = {
		studentID = 5012,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[138] = {
		studentID = 5012,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[139] = {
		studentID = 5012,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[140] = {
		studentID = 5012,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[141] = {
		studentID = 5012,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[142] = {
		studentID = 5012,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[143] = {
		studentID = 5012,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[144] = {
		studentID = 5012,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[145] = {
		studentID = 5012,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[146] = {
		studentID = 5012,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[147] = {
		studentID = 5012,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[148] = {
		studentID = 5012,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[149] = {
		studentID = 5012,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[150] = {
		studentID = 5012,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[151] = {
		studentID = 5012,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[152] = {
		studentID = 5012,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[153] = {
		studentID = 5012,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[154] = {
		studentID = 5013,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[155] = {
		studentID = 5013,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[156] = {
		studentID = 5013,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[157] = {
		studentID = 5013,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[158] = {
		studentID = 5013,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[159] = {
		studentID = 5013,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[160] = {
		studentID = 5013,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[161] = {
		studentID = 5013,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[162] = {
		studentID = 5013,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[163] = {
		studentID = 5013,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[164] = {
		studentID = 5013,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[165] = {
		studentID = 5013,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[166] = {
		studentID = 5013,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[167] = {
		studentID = 5013,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[168] = {
		studentID = 5013,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[169] = {
		studentID = 5013,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[170] = {
		studentID = 5013,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[171] = {
		studentID = 5013,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[172] = {
		studentID = 5014,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[173] = {
		studentID = 5014,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[174] = {
		studentID = 5014,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[175] = {
		studentID = 5014,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[176] = {
		studentID = 5014,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[177] = {
		studentID = 5014,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[178] = {
		studentID = 5014,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[179] = {
		studentID = 5014,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[180] = {
		studentID = 5014,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[181] = {
		studentID = 5014,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[182] = {
		studentID = 5014,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[183] = {
		studentID = 5014,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[184] = {
		studentID = 5014,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[185] = {
		studentID = 5014,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[186] = {
		studentID = 5014,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[187] = {
		studentID = 5014,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[188] = {
		studentID = 5014,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[189] = {
		studentID = 5014,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[190] = {
		studentID = 5015,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[191] = {
		studentID = 5015,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[192] = {
		studentID = 5015,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[193] = {
		studentID = 5015,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[194] = {
		studentID = 5015,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[195] = {
		studentID = 5015,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[196] = {
		studentID = 5015,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[197] = {
		studentID = 5015,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[198] = {
		studentID = 5015,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[199] = {
		studentID = 5015,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[200] = {
		studentID = 5015,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[201] = {
		studentID = 5015,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[202] = {
		studentID = 5015,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[203] = {
		studentID = 5015,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[204] = {
		studentID = 5015,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[205] = {
		studentID = 5015,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[206] = {
		studentID = 5015,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[207] = {
		studentID = 5015,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[208] = {
		studentID = 5016,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[209] = {
		studentID = 5016,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[210] = {
		studentID = 5016,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[211] = {
		studentID = 5016,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[212] = {
		studentID = 5016,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[213] = {
		studentID = 5016,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[214] = {
		studentID = 5016,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[215] = {
		studentID = 5016,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[216] = {
		studentID = 5016,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[217] = {
		studentID = 5016,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[218] = {
		studentID = 5016,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[219] = {
		studentID = 5016,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[220] = {
		studentID = 5016,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[221] = {
		studentID = 5016,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[222] = {
		studentID = 5016,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[223] = {
		studentID = 5016,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[224] = {
		studentID = 5016,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[225] = {
		studentID = 5016,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[226] = {
		studentID = 5017,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[227] = {
		studentID = 5017,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[228] = {
		studentID = 5017,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[229] = {
		studentID = 5017,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[230] = {
		studentID = 5017,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[231] = {
		studentID = 5017,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[232] = {
		studentID = 5017,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[233] = {
		studentID = 5017,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[234] = {
		studentID = 5017,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[235] = {
		studentID = 5017,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[236] = {
		studentID = 5017,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[237] = {
		studentID = 5017,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[238] = {
		studentID = 5017,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[239] = {
		studentID = 5017,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[240] = {
		studentID = 5017,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[241] = {
		studentID = 5017,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[242] = {
		studentID = 5017,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[243] = {
		studentID = 5017,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
	[244] = {
		studentID = 5018,
		giftType = 1,
		content = "这，要给我吗，谢谢。",
		level = 0,
	},
	[245] = {
		studentID = 5018,
		giftType = 2,
		content = "诶，老师怎么知道我喜欢这个。",
		level = 0,
	},
	[246] = {
		studentID = 5018,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 0,
	},
	[247] = {
		studentID = 5018,
		giftType = 1,
		content = "啊，谢谢老师。",
		level = 1,
	},
	[248] = {
		studentID = 5018,
		giftType = 2,
		content = "谢谢老师，我很喜欢。",
		level = 1,
	},
	[249] = {
		studentID = 5018,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 1,
	},
	[250] = {
		studentID = 5018,
		giftType = 1,
		content = "啊，给我的吗？",
		level = 2,
	},
	[251] = {
		studentID = 5018,
		giftType = 2,
		content = "哇，谢谢老师！",
		level = 2,
	},
	[252] = {
		studentID = 5018,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 2,
	},
	[253] = {
		studentID = 5018,
		giftType = 1,
		content = "这个，还是谢谢老师。",
		level = 3,
	},
	[254] = {
		studentID = 5018,
		giftType = 2,
		content = "谢谢，总感觉已经被老师看穿了。",
		level = 3,
	},
	[255] = {
		studentID = 5018,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 3,
	},
	[256] = {
		studentID = 5018,
		giftType = 1,
		content = "哈，谢谢老师。",
		level = 4,
	},
	[257] = {
		studentID = 5018,
		giftType = 2,
		content = "一直想要这个，谢谢老师！",
		level = 4,
	},
	[258] = {
		studentID = 5018,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 4,
	},
	[259] = {
		studentID = 5018,
		giftType = 1,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[260] = {
		studentID = 5018,
		giftType = 2,
		content = "都这么熟了，就别那么客气啦。",
		level = 5,
	},
	[261] = {
		studentID = 5018,
		giftType = 3,
		content = "虽然没兴趣，不过还是谢谢老师。",
		level = 5,
	},
}
