-- id                               int                              道具ID
-- type                             int                              道具类型 （1：赠送道具，2：装备道具，3：自用道具）
-- subType                          int                              子类型
-- unlockType                       int                              解锁条件1 回合解锁 2技能解锁
-- round                            int                              解锁回合
-- name                             string                           名称
-- desc                             string                           描述
-- icon                             string                           图标
-- buyPrice                         int                              价格
-- Number                           int                              数量
-- attributes                       array[int:6]                     学生属性提升
--    [1]                           int                              好感度
--    [2]                           int                              压力值
--    [3]                           int                              语文成绩
--    [4]                           int                              数学成绩
--    [5]                           int                              英语成绩
--    [6]                           int                              综合成绩
-- talent                           array[float:4]                   学生天赋提升
--    [1]                           float                            语文成绩
--    [2]                           float                            数学成绩
--    [3]                           float                            英语成绩
--    [4]                           float                            综合成绩
-- teacher                          array[float:5]                   老师属性
--    [1]                           float                            老师精力
--    [2]                           float                            洞察经验
--    [3]                           float                            情商经验
--    [4]                           float                            教学经验
--    [5]                           float                            精力经验
-- sustain                          int                              持续回合
-- target                           string                           作用对象

return {
	[10000] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 1,
		name = "数学模拟卷",
		desc = "本市老师联合出版的阶段性模拟卷，包括很多详细知识点，如果能好好做完应该能够提升数学成绩。",
		icon = "item1",
		buyPrice = 800,
		Number = 5,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 2,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10001] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 20,
		name = "名校数学模拟卷",
		desc = "国内知名高校出版的模拟卷，甚至有高考出题人参与编写，内含详细讲解，如果能好好做完应该能够大幅提升数学成绩。",
		icon = "item2",
		buyPrice = 2000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 5,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10002] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 1,
		name = "语文模拟卷",
		desc = "本市老师联合出版的阶段性模拟卷，包括很多详细知识点，如果能好好做完应该能够提升语文成绩。",
		icon = "item3",
		buyPrice = 800,
		Number = 5,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 2,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10003] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 20,
		name = "名校语文模拟卷",
		desc = "国内知名高校出版的模拟卷，甚至有高考出题人参与编写，内含详细讲解，如果能好好做完应该能够大幅提升语文成绩。",
		icon = "item4",
		buyPrice = 2000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 5,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10004] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 1,
		name = "英语模拟卷",
		desc = "本市老师联合出版的阶段性模拟卷，包括很多详细知识点，如果能好好做完应该能够提升英语成绩。",
		icon = "item5",
		buyPrice = 800,
		Number = 5,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 0,
			[5] = 2,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10005] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 20,
		name = "名校英语模拟卷",
		desc = "国内知名高校出版的模拟卷，甚至有高考出题人参与编写，内含详细讲解，如果能好好做完应该能够大幅提升英语成绩。",
		icon = "item6",
		buyPrice = 2000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 0,
			[5] = 5,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10006] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 1,
		name = "综合模拟卷",
		desc = "本市老师联合出版的阶段性模拟卷，包括很多详细知识点，如果能好好做完应该能够提升综合成绩。",
		icon = "item7",
		buyPrice = 800,
		Number = 5,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 2,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10007] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 20,
		name = "名校综合模拟卷",
		desc = "国内知名高校出版的模拟卷，甚至有高考出题人参与编写，内含详细讲解，如果能好好做完应该能够大幅提升综合成绩。",
		icon = "item8",
		buyPrice = 2000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 5,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10008] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 1,
		name = "漫画巴士",
		desc = "备受青少年欢迎的漫画周刊，许多当下颇有人气的漫画都有在上面连载，能让学生从紧张的学习中获得片刻放松。",
		icon = "item9",
		buyPrice = 1000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = -4,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10009] = {
		type = 2,
		subType = -1,
		unlockType = -1,
		round = -1,
		name = "班主任的钢笔",
		desc = "李自言老师任教时最喜欢的钢笔，虽然保护的很好但仍有使用的痕迹，握着它仿佛能感受到某种重量。获取后能够提升老师获得的教学经验。",
		icon = "item10",
		buyPrice = 6000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = 1.4,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10010] = {
		type = 2,
		subType = -1,
		unlockType = -1,
		round = -1,
		name = "平板电脑",
		desc = "在宿舍忙里偷闲时必备神器，能大大提升刷剧追番的体验，还能及时了解时下新梗不至于和学生脱节。获取后能够提升获得的洞察经验。",
		icon = "item11",
		buyPrice = 6000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = 1.4,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10011] = {
		type = 2,
		subType = -1,
		unlockType = -1,
		round = -1,
		name = "运动跑鞋",
		desc = "专为跑步设计的运动鞋，轻便透气减震效果极佳，穿上它感觉能多跑10公里！获取后能够提升获得的精力经验。",
		icon = "item12",
		buyPrice = 6000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = 1.4,
		},
		sustain = -1,
		target = "-1",
	},
	[10012] = {
		type = 2,
		subType = -1,
		unlockType = -1,
		round = -1,
		name = "龙井茶",
		desc = "办公室的老师们喜茶，龙井浓郁但清爽的香气总是引来其他老师，以茶会友时也能顺便偷学与学生相处的经验。获取后能提升获得的情商经验。",
		icon = "item13",
		buyPrice = 6000,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = 1.4,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10013] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 1,
		name = "招牌鸡腿",
		desc = "小卖部的招牌美食，外酥里嫩香气四溢的鸡腿在其他学校中也有颇有名气。赠予后能够稍微提升学生的好感度。",
		icon = "item14",
		buyPrice = 500,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10014] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 1,
		name = "奶茶",
		desc = "小卖部自制的奶茶，赠予后除了提升好感度外还能降低学生的压力。",
		icon = "item15",
		buyPrice = 1500,
		Number = 1,
		attributes = {
			[1] = 1,
			[2] = -5,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10015] = {
		type = 1,
		subType = -1,
		unlockType = 2,
		round = 1019,
		name = "数学复习大纲",
		desc = "上届状元的复习心得，能够提升学生的数学天赋。",
		icon = "item16",
		buyPrice = 8888,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0.2,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10016] = {
		type = 1,
		subType = -1,
		unlockType = 2,
		round = 1019,
		name = "语文复习大纲",
		desc = "上届状元的复习心得，能够提升学生的语文天赋。",
		icon = "item17",
		buyPrice = 8888,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0.2,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10017] = {
		type = 1,
		subType = -1,
		unlockType = 2,
		round = 1019,
		name = "英语复习大纲",
		desc = "上届状元的复习心得，能够提升学生的英语天赋。",
		icon = "item18",
		buyPrice = 8888,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0.2,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10018] = {
		type = 1,
		subType = -1,
		unlockType = 2,
		round = 1019,
		name = "综合复习大纲",
		desc = "上届状元的复习心得，能够提升学生的综合天赋。",
		icon = "item19",
		buyPrice = 8888,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0.2,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10019] = {
		type = 3,
		subType = -1,
		unlockType = 1,
		round = 3,
		name = "浓缩咖啡",
		desc = "高浓度无糖咖啡，提神醒脑的饮品，使用后能够恢复老师自身的精力。",
		icon = "item20",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = 4,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10020] = {
		type = 3,
		subType = -1,
		unlockType = 1,
		round = 10,
		name = "风油精",
		desc = "传说中提神醒脑的神器，对精神层面有极大杀伤力。使用后能够大幅恢复老师自身的精力。",
		icon = "item21",
		buyPrice = 1500,
		Number = 1,
		attributes = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = 10,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "-1",
	},
	[10021] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "圆规",
		desc = "对理科感兴趣的同学可能会喜欢",
		icon = "item22",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5018;5013;5015",
	},
	[10022] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "畅销小说",
		desc = "对文科感兴趣的同学可能会喜欢",
		icon = "item23",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5010;5012;5017",
	},
	[10023] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "小蛋糕",
		desc = "平时爱吃甜食的同学可能会喜欢",
		icon = "item24",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5014;5010;5018",
	},
	[10024] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "星球挂件",
		desc = "对宇宙科幻感兴趣的同学可能会喜欢",
		icon = "item25",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5018;5017;5015",
	},
	[10025] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "U形枕",
		desc = "材质绵软的U形枕头，爱睡觉打瞌睡的同学应该很需要。",
		icon = "item26",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5014;5018",
	},
	[10026] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "橡胶手环",
		desc = "热爱运动的同学可能会喜欢",
		icon = "item27",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5015;5016",
	},
	[10027] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "薄荷含片",
		desc = "经常用嗓子的同学可能会喜欢",
		icon = "item28",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5013;5011",
	},
	[10028] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "游戏点卡",
		desc = "经常打游戏的同学可能会喜欢",
		icon = "item29",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5011;5015;5017",
	},
	[10029] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "动漫周边",
		desc = "对二次元感兴趣的同学可能会喜欢",
		icon = "item30",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5011;5014;5015",
	},
	[10030] = {
		type = 1,
		subType = -1,
		unlockType = 1,
		round = 5,
		name = "奖状",
		desc = "希望被认可的同学可能会喜欢",
		icon = "item31",
		buyPrice = 1000,
		Number = 5,
		attributes = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 0,
			[5] = 0,
			[6] = 0,
		},
		talent = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		teacher = {
			[1] = -1,
			[2] = -1,
			[3] = -1,
			[4] = -1,
			[5] = -1,
		},
		sustain = -1,
		target = "5017;5013;5012",
	},
}
