-- id                               int                              技能ID
-- skillType                        int                              从属类型
-- level                            int                              解锁等级
-- name                             string                           名称
-- desc                             string                           描述
-- targetType                       int                              目标类型
-- target                           array[int:3]                     目标
--    [1]                           int                              
--    [2]                           int                              
--    [3]                           int                              
-- icon                             string                           图标

return {
	[1001] = {
		skillType = 1,
		level = 1,
		name = "Lv1",
		desc = "主动技：任意挪动两个相邻方块（20次消除后可再次使用）",
		targetType = 11,
		target = {
			[1] = 1,
			[2] = 1,
			[3] = -1,
		},
		icon = "skill1",
	},
	[1002] = {
		skillType = 1,
		level = 2,
		name = "Lv2",
		desc = "解锁档案界面切换立绘功能",
		targetType = 21,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill4",
	},
	[1003] = {
		skillType = 1,
		level = 3,
		name = "Lv3",
		desc = "神秘格子出现增益效果几率增加",
		targetType = 22,
		target = {
			[1] = 1,
			[2] = 25,
			[3] = -1,
		},
		icon = "skill4",
	},
	[1004] = {
		skillType = 1,
		level = 4,
		name = "Lv4",
		desc = "主动技：击碎一个指定方块（10次消除后可再次使用）",
		targetType = 11,
		target = {
			[1] = 1,
			[2] = 2,
			[3] = -1,
		},
		icon = "skill2",
	},
	[1005] = {
		skillType = 1,
		level = 5,
		name = "Lv5",
		desc = "赠与道具额外获得2点好感度",
		targetType = 23,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill4",
	},
	[1006] = {
		skillType = 1,
		level = 6,
		name = "Lv6",
		desc = "未使用的工资每回合获得利息",
		targetType = 24,
		target = {
			[1] = 5,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill4",
	},
	[1007] = {
		skillType = 1,
		level = 7,
		name = "Lv7",
		desc = "主动技：特殊方块被道具波及后会获得该道具效果",
		targetType = 11,
		target = {
			[1] = 1,
			[2] = 3,
			[3] = -1,
		},
		icon = "skill3",
	},
	[1008] = {
		skillType = 1,
		level = 8,
		name = "Lv8",
		desc = "开局在随机位置生成两个道具",
		targetType = 25,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill4",
	},
	[1009] = {
		skillType = 1,
		level = 9,
		name = "Lv9",
		desc = "小游戏可以跳过，分数根据各属性等级结算（8级获得全额奖励）",
		targetType = 26,
		target = {
			[1] = 2,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill4",
	},
	[1010] = {
		skillType = 1,
		level = 10,
		name = "Lv10",
		desc = "目标达成后自动消除的格子按高倍计算",
		targetType = 27,
		target = {
			[1] = 200,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill4",
	},
	[1011] = {
		skillType = 2,
		level = 1,
		name = "Lv1",
		desc = "主动技：玩家球获得持续10s的磁力（30s冷却）",
		targetType = 11,
		target = {
			[1] = 2,
			[2] = 1,
			[3] = -1,
		},
		icon = "skill5",
	},
	[1012] = {
		skillType = 2,
		level = 2,
		name = "Lv2",
		desc = "特殊加分点出现几率增加",
		targetType = 31,
		target = {
			[1] = 10,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill8",
	},
	[1013] = {
		skillType = 2,
		level = 3,
		name = "Lv3",
		desc = "商店购物打9折",
		targetType = 32,
		target = {
			[1] = 9,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill8",
	},
	[1014] = {
		skillType = 2,
		level = 4,
		name = "Lv4",
		desc = "主动技：纸飞机获得持续10s的加速效果（30s冷却）",
		targetType = 11,
		target = {
			[1] = 2,
			[2] = 2,
			[3] = -1,
		},
		icon = "skill6",
	},
	[1015] = {
		skillType = 2,
		level = 5,
		name = "Lv5",
		desc = "漏掉分数点不扣分",
		targetType = 33,
		target = {
			[1] = 30,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill8",
	},
	[1016] = {
		skillType = 2,
		level = 6,
		name = "Lv6",
		desc = "开导高压力学生额外降低压力",
		targetType = 34,
		target = {
			[1] = 60,
			[2] = 3,
			[3] = -1,
		},
		icon = "skill8",
	},
	[1017] = {
		skillType = 2,
		level = 7,
		name = "Lv7",
		desc = "主动技：吸收当前屏幕内的所有加分点（60秒冷却）",
		targetType = 11,
		target = {
			[1] = 2,
			[2] = 3,
			[3] = -1,
		},
		icon = "skill7",
	},
	[1018] = {
		skillType = 2,
		level = 8,
		name = "Lv8",
		desc = "完成课外活动所有角色额外获得2点好感度",
		targetType = 35,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill8",
	},
	[1019] = {
		skillType = 2,
		level = 9,
		name = "Lv9",
		desc = "解锁商店特殊道具",
		targetType = 36,
		target = {
			[1] = 10029,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill8",
	},
	[1020] = {
		skillType = 2,
		level = 10,
		name = "Lv10",
		desc = "每回合结算时所有角色额外降低1点压力",
		targetType = 37,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill8",
	},
	[1021] = {
		skillType = 3,
		level = 1,
		name = "Lv1",
		desc = "主动技：沿视线扔出粉笔击碎任何障碍（30秒冷却，可储存两发）",
		targetType = 11,
		target = {
			[1] = 3,
			[2] = 1,
			[3] = -1,
		},
		icon = "skill9",
	},
	[1022] = {
		skillType = 3,
		level = 2,
		name = "Lv2",
		desc = "空钩视线收回速度加快",
		targetType = 41,
		target = {
			[1] = 2,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill12",
	},
	[1023] = {
		skillType = 3,
		level = 3,
		name = "Lv3",
		desc = "增加视线长度",
		targetType = 42,
		target = {
			[1] = 80,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill12",
	},
	[1024] = {
		skillType = 3,
		level = 4,
		name = "Lv4",
		desc = "主动技：降低视线晃动速度，出手3次后解除（60秒冷却）",
		targetType = 11,
		target = {
			[1] = 3,
			[2] = 2,
			[3] = -1,
		},
		icon = "skill10",
	},
	[1025] = {
		skillType = 3,
		level = 5,
		name = "Lv5",
		desc = "干扰气泡移动速度降低",
		targetType = 43,
		target = {
			[1] = 30,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill12",
	},
	[1026] = {
		skillType = 3,
		level = 6,
		name = "Lv6",
		desc = "辅导答对额外获得1分",
		targetType = 44,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill12",
	},
	[1027] = {
		skillType = 3,
		level = 7,
		name = "Lv7",
		desc = "主动技：击破所有干扰气泡（60秒冷却）",
		targetType = 11,
		target = {
			[1] = 3,
			[2] = 3,
			[3] = -1,
		},
		icon = "skill11",
	},
	[1028] = {
		skillType = 3,
		level = 8,
		name = "Lv8",
		desc = "考试失常几率下降10%",
		targetType = 45,
		target = {
			[1] = 10,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill12",
	},
	[1029] = {
		skillType = 3,
		level = 9,
		name = "Lv9",
		desc = "学生弱势科目成绩提升+20%",
		targetType = 46,
		target = {
			[1] = 1,
			[2] = 20,
			[3] = -1,
		},
		icon = "skill12",
	},
	[1030] = {
		skillType = 3,
		level = 10,
		name = "Lv10",
		desc = "专心度高于80则按100%转换",
		targetType = 47,
		target = {
			[1] = 80,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill12",
	},
	[1031] = {
		skillType = 4,
		level = 1,
		name = "Lv1",
		desc = "获得5点初始精力上限",
		targetType = 51,
		target = {
			[1] = 5,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1032] = {
		skillType = 4,
		level = 2,
		name = "Lv2",
		desc = "精力上限+1",
		targetType = 52,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1033] = {
		skillType = 4,
		level = 3,
		name = "Lv3",
		desc = "精力上限+1",
		targetType = 52,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1034] = {
		skillType = 4,
		level = 4,
		name = "Lv4",
		desc = "备课初始步数+5",
		targetType = 53,
		target = {
			[1] = 5,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1035] = {
		skillType = 4,
		level = 5,
		name = "Lv5",
		desc = "精力上限+1",
		targetType = 52,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1036] = {
		skillType = 4,
		level = 6,
		name = "Lv6",
		desc = "晚自习时间延长15s",
		targetType = 54,
		target = {
			[1] = 15,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1037] = {
		skillType = 4,
		level = 7,
		name = "Lv7",
		desc = "精力上限+1",
		targetType = 52,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1038] = {
		skillType = 4,
		level = 8,
		name = "Lv8",
		desc = "课外活动时间延长15s",
		targetType = 55,
		target = {
			[1] = 15,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1039] = {
		skillType = 4,
		level = 9,
		name = "Lv9",
		desc = "精力上限+1",
		targetType = 52,
		target = {
			[1] = 1,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
	[1040] = {
		skillType = 4,
		level = 10,
		name = "Lv10",
		desc = "所有技能冷却降低50%",
		targetType = 56,
		target = {
			[1] = 50,
			[2] = -1,
			[3] = -1,
		},
		icon = "skill13",
	},
}
